- name: Patch Move Hub Config
      run: |
        CONFIG_FILE="bricks/movehub/mpconfigport.h"
        
        cat << 'EOF' >> "$CONFIG_FILE"
        
        /* Custom Additions for usys and uselect */
        #undef MICROPY_PY_SYS
        #define MICROPY_PY_SYS (1)
        
        #undef MICROPY_PY_USELECT
        #define MICROPY_PY_USELECT (1)

        /* Required dependency for MICROPY_PY_SYS */
        #define MICROPY_MODULE_ATTR_DELEGATION (1)
        
        /* Disabling heavy features to make space in Flash memory */
        #undef PYBRICKS_PY_EV3DEVICES
        #define PYBRICKS_PY_EV3DEVICES (0)
        
        #undef PYBRICKS_PY_PUPDEVICES
        #define PYBRICKS_PY_PUPDEVICES (0)

        #undef MICROPY_PY_BUILTINS_REVERSED
        #define MICROPY_PY_BUILTINS_REVERSED (0)
        
        #undef MICROPY_PY_BUILTINS_STR_COUNT
        #define MICROPY_PY_BUILTINS_STR_COUNT (0)

        #undef MICROPY_PY_BUILTINS_SET
        #define MICROPY_PY_BUILTINS_SET (0)
        EOF
